const data = {
  projects: [
    {
      key: 0,
      projectName: 'Financial Metrics',
      projectImageMobile: './projects/FinancialMetrices.png',
      projectImageDesktop: './projects/FinancialMetrices.png',
      companyName: 'MICROVERSE',
      projectPosition: 'Front End Dev',
      projectDate: 2022,
      projectDescription: 'This capstone project is about building a mobile web application to check a list of metrics (numeric values). It was created making use of React and Redux.',
      projectTechnologies: ['ReactJS', 'Redux', 'JavaScript', 'CSS', 'HTML', 'GitFlow'],
      projectTextMobile: 'This capstone project is about building a mobile web application to check a list of metrics (numeric values). It was created making use of React and Redux.',
      projectTextDesktop:
        'This capstone project is about building a mobile web application to check a list of metrics (numeric values). It was created making use of React and Redux.',
      seeLive: './images/seeLive.png',
      seeSource: './images/seeSource.png',
      seeLivePage: 'https://amrendrakind.github.io/financial-metrics/',
      seeSourceCode: 'https://github.com/amrendrakind/financial-metrics/',
    },
    {
      key: 1,
      projectName: 'Space Travelers',
      projectImageMobile: './projects/SpaceTravellersHub.png',
      projectImageDesktop: './projects/SpaceTravellersHub.png',
      companyName: 'MICROVERSE',
      projectPosition: 'Front End Dev',
      projectDate: 2022,
      projectDescription: 'The Space Travellers Hub is a web application that provides commercial and scientific space travel services. This application will allow users to book rockets and join selected space missions.',
      projectTechnologies: ['ReactJS', 'Redux', 'JavaScript', 'CSS', 'HTML', 'GitFlow'],
      projectTextMobile: 'The Space Travellers Hub is a web application that provides commercial and scientific space travel services. This application will allow users to book rockets and join selected space missions.',
      projectTextDesktop:
        'The Space Travellers Hub is a web application that provides commercial and scientific space travel services. This application will allow users to book rockets and join selected space missions.'
        + 'User can go to My Profile that section displays all reserved rockets and space missions.'
        + 'User can join missions if they wish.'
        + 'Users can book each rocket by clicking the reservation button or cancel the previously made booking.',
      seeLive: './images/seeLive.png',
      seeSource: './images/seeSource.png',
      seeLivePage: 'https://amrendrakind.github.io/space-travelers/',
      seeSourceCode: 'https://github.com/amrendrakind/space-travelers/',
    },
    {
      key: 2,
      projectName: 'BookStore',
      projectImageMobile: './projects/Bookstore.png',
      projectImageDesktop: './projects/Bookstore.png',
      companyName: 'MICROVERSE',
      projectPosition: 'Front End Dev',
      projectDate: 2022,
      projectDescription: 'This project is for Bookstore MVP version website. It will Display a list of books, Add a book, Remove a selected book. I will use use React and Redux.',
      projectTechnologies: ['ReactJS', 'Redux', 'JavaScript', 'CSS', 'HTML', 'GitFlow'],
      projectTextMobile: 'This project is for Bookstore MVP version website. It will Display a list of books, Add a book, Remove a selected book. I will use use React and Redux.',
      projectTextDesktop:
        'The Bookstore is a website similar to the "Awesome Books" website built in the previous module. I will create an MVP version of it that allows you to:'
        + 'Display a list of books.'
        + 'Add a book.'
        + 'Remove a selected book.',
      seeLive: './images/seeLive.png',
      seeSource: './images/seeSource.png',
      seeLivePage: 'https://amrendrakind.github.io/bookstore-react/',
      seeSourceCode: 'https://github.com/amrendrakind/bookstore-react/',
    },
    {
      key: 3,
      projectName: 'Math Magicians',
      projectImageMobile: './projects/Match-Magician.png',
      projectImageDesktop: './projects/Match-Magician.png',
      companyName: 'MICROVERSE',
      projectPosition: 'Front End Dev',
      projectDate: 2022,
      projectDescription: '"Math Magicians" is a website for all fans of mathematics. It is a Single Page App (SPA) that allows users to: Make simple calculations. Read a random maths-related quote.',
      projectTechnologies: ['ReactJS', 'JavaScript', 'CSS', 'HTML', 'Webpack', 'GitFlow'],
      projectTextMobile: '"Math Magicians" is a website for all fans of mathematics. It is a Single Page App (SPA) that allows users to: Make simple calculations. Read a random maths-related quote.',
      projectTextDesktop:
        '"Math Magicians" is a website for all fans of mathematics. It is a Single Page App (SPA) that allows users to: Make simple calculations. Read a random maths-related quote.',
      seeLive: './images/seeLive.png',
      seeSource: './images/seeSource.png',
      seeLivePage: 'https://amrendrakind.github.io/math-magicians/',
      seeSourceCode: 'https://github.com/amrendrakind/math-magicians/',
    },
    {
      key: 4,
      projectName: 'Movie Shows',
      projectImageMobile: './projects/MovieShows.png',
      projectImageDesktop: './projects/MovieShows.png',
      companyName: 'MICROVERSE',
      projectPosition: 'Front End Dev',
      projectDate: 2022,
      projectDescription: 'Movie Shows capstone project is about building your web application based on an external API. We will select an API that provides data about a topic that we like and then build the webapp around it.',
      projectTechnologies: ['JavaScript', 'CSS', 'HTML', 'Webpack', 'GitFlow'],
      projectTextMobile: 'Movie Shows capstone project is about building your web application based on an external API. We will select an API that provides data about a topic that we like and then build the webapp around it.',
      projectTextDesktop:
        'Movie Shows capstone project is about building your web application based on an external API. We will select an API that provides data about a topic that we like and then build the webapp around it.',
      seeLive: './images/seeLive.png',
      seeSource: './images/seeSource.png',
      seeLivePage: 'https://amrendrakind.github.io/API-based-webapp/',
      seeSourceCode: 'https://github.com/amrendrakind/API-based-webapp/',
    },
    {
      key: 5,
      projectName: 'ToDo Lists',
      projectImageMobile: './projects/ToDoList.png',
      projectImageDesktop: './projects/ToDoList.png',
      companyName: 'MICROVERSE',
      projectPosition: 'Front End Dev',
      projectDate: 2022,
      projectDescription: '"To-Do List" is a tool that helps to organize your day. It simply lists the things that you need to do and allows you to mark them as complete. I build a simple website that allows for doing that, and did it using ES6 and Webpack!',
      projectTechnologies: ['JavaScript', 'CSS', 'HTML', 'Webpack', 'ES6', 'GitFlow'],
      projectTextMobile: '"To-Do List" is a tool that helps to organize your day. It simply lists the things that you need to do and allows you to mark them as complete. I build a simple website that allows for doing that, and did it using ES6 and Webpack!',
      projectTextDesktop:
        '"To-Do List" is a tool that helps to organize your day. It simply lists the things that you need to do and allows you to mark them as complete. I build a simple website that allows for doing that, and did it using ES6 and Webpack!',
      seeLive: './images/seeLive.png',
      seeSource: './images/seeSource.png',
      seeLivePage: 'https://amrendrakind.github.io/ToDoList/',
      seeSourceCode: 'https://github.com/amrendrakind/ToDoList/',
    },
    {
      key: 6,
      projectName: 'Awesome Books',
      projectImageMobile: './projects/AwesomeBooks.png',
      projectImageDesktop: './projects/AwesomeBooks.png',
      companyName: 'MICROVERSE',
      projectPosition: 'Front End Dev',
      projectDate: 2022,
      projectDescription: '"Awesome books" is a simple website that displays a list of books and allows you to add and remove books from that list. By building this application, you will learn how to manage data using JavaScript.',
      projectTechnologies: ['JavaScript', 'CSS', 'HTML', 'Webpack', 'ES6', 'GitFlow'],
      projectTextMobile: '"Awesome books" is a simple website that displays a list of books and allows you to add and remove books from that list. By building this application, you will learn how to manage data using JavaScript.',
      projectTextDesktop:
        '"Awesome books" is a simple website that displays a list of books and allows you to add and remove books from that list. By building this application, you will learn how to manage data using JavaScript.',
      seeLive: './images/seeLive.png',
      seeSource: './images/seeSource.png',
      seeLivePage: 'https://amrendrakind.github.io/AwesomeBooks_ES6/',
      seeSourceCode: 'https://github.com/amrendrakind/AwesomeBooks_ES6/',
    },
    {
      key: 7,
      projectName: 'Conference Page',
      projectImageMobile: './projects/ConferencePage.png',
      projectImageDesktop: './projects/ConferencePage.png',
      companyName: 'MICROVERSE',
      projectPosition: 'Front End Dev',
      projectDate: 2022,
      projectDescription: 'In this Conference Page capstone project We are going to build is based on an online website for a conference.',
      projectTechnologies: ['JavaScript', 'CSS', 'HTML', 'GitFlow'],
      projectTextMobile: 'In this Conference Page capstone project We are going to build is based on an online website for a conference.',
      projectTextDesktop:
        'In this Conference Page capstone project We are going to build is based on an online website for a conference.',
      seeLive: './images/seeLive.png',
      seeSource: './images/seeSource.png',
      seeLivePage: 'https://amrendrakind.github.io/conferencePage_capstoneProject/',
      seeSourceCode: 'https://github.com/amrendrakind/conferencePage_capstoneProject/',
    },
  ],
};
export default data;
